### ISSUE TITLE
Cabinets are a bit wider and taller than a node

### ISSUE THREAD

**Issue by Montandalar** [danil275487/minetest-filecabinet#2]
Because of their extra size, cabinets can overlap adjacent nodes and will cause z-fighting with each other. If you need to keep the pixel dimensions the exact same for an accurate windows 3.1 experience, I guess the fix is to make a mesh and scale it down so it fits. The current textures don't align with the 16px grid of other blocks though, so maybe that's the way to go.
![screenshot_20220104_135859](https://user-images.githubusercontent.com/13659694/148004490-b30bd8ea-699c-412c-aa9c-ec55ca323e1e.png)

**Comment by danil275487** [comment]
I know all of theese issues however there isnt really any ideal solution to this, except if I hack up a custom texture+mesh that is 1x2 nodes instead of 1.1x1.5, wich will look quite ugly.
